In [1]:
import torch
import numpy as py
torch.__version__

'1.13.1+cu117'

In [2]:
x = torch.rand(2,3)

In [3]:
x

tensor([[0.5784, 0.4123, 0.2231],
        [0.4537, 0.6358, 0.1939]])

In [4]:
x.shape

torch.Size([2, 3])

In [5]:
x.size()


torch.Size([2, 3])

张量（Tensor）是一个定义在一些向量空间和一些对偶空间的笛卡儿积上的多重线性映射，其坐标是|n|维空间内，有|n|个分量的一种量， 其中每个分量都是坐标的函数， 而在坐标变换时，这些分量也依照某些规则作线性变换。r称为该张量的秩或阶（与矩阵的秩和阶均无关系）

In [6]:
y = torch.rand(2,3,4,5)
y

tensor([[[[0.7196, 0.5126, 0.4991, 0.1523, 0.0395],
          [0.8169, 0.5040, 0.8185, 0.1181, 0.9946],
          [0.0298, 0.8227, 0.1116, 0.9136, 0.3894],
          [0.2067, 0.1000, 0.2255, 0.8508, 0.1310]],

         [[0.2584, 0.7739, 0.2133, 0.0789, 0.3132],
          [0.7089, 0.9375, 0.5544, 0.8672, 0.7116],
          [0.6296, 0.4132, 0.5092, 0.2124, 0.0025],
          [0.7272, 0.1717, 0.3788, 0.7206, 0.8492]],

         [[0.4471, 0.7634, 0.8094, 0.5984, 0.4939],
          [0.0640, 0.1260, 0.1961, 0.1905, 0.5352],
          [0.2561, 0.3946, 0.9267, 0.0191, 0.3424],
          [0.8311, 0.2403, 0.6208, 0.6824, 0.4202]]],


        [[[0.3698, 0.2067, 0.6463, 0.4600, 0.5542],
          [0.9718, 0.6777, 0.0632, 0.3495, 0.0808],
          [0.7414, 0.8582, 0.7690, 0.9284, 0.7386],
          [0.0818, 0.8886, 0.0865, 0.8871, 0.6880]],

         [[0.6814, 0.1142, 0.7833, 0.8025, 0.1518],
          [0.0647, 0.2580, 0.3532, 0.5132, 0.3050],
          [0.3867, 0.1963, 0.5243, 0.8346, 0.9438],
  

In [7]:
y.shape

torch.Size([2, 3, 4, 5])

在同构的意义下，第零阶张量 （r = 0） 为标量 （Scalar），第一阶张量 （r = 1） 为向量 （Vector）， 第二阶张量 （r = 2） 则成为矩阵 （Matrix），第三阶以上的统称为多维张量。

In [8]:
scalar = torch.tensor(3.14159)
scalar

tensor(3.1416)

In [9]:
scalar.shape

torch.Size([])

In [10]:
scalar.size()

torch.Size([])

In [11]:
#对与标量，我们可以使用.item()从中取出对应的python对象的数值
scalar.item()

3.141590118408203

In [12]:
#特别的：如果张量中只有一个元素的tensor也可以调用tensor.item方法
tensor = torch.tensor([3.14])
tensor.shape


torch.Size([1])

In [13]:
tensor.item()

3.140000104904175

基本类型
Tensor的基本数据类型有五种：

32位浮点型：torch.FloatTensor。 (默认)
64位整型：torch.LongTensor。
32位整型：torch.IntTensor。
16位整型：torch.ShortTensor。
64位浮点型：torch.DoubleTensor。
除以上数字类型外，还有 byte和chart型

In [14]:
long = tensor.long()
long

tensor([3])

In [15]:
half = tensor.half()
half

tensor([3.1406], dtype=torch.float16)

In [16]:
int_t = tensor.int()

In [17]:
int_t

tensor([3], dtype=torch.int32)

In [18]:
flo = tensor.float()

In [19]:
flo

tensor([3.1400])

In [20]:
short = tensor.short()

In [21]:
short

tensor([3], dtype=torch.int16)

In [22]:
ch = tensor.char()

In [23]:
ch

tensor([3], dtype=torch.int8)

In [24]:
bt = tensor.byte()
bt

tensor([3], dtype=torch.uint8)

Numpy转换
使用numpy方法将Tensor转为ndarray

In [25]:
a  = torch.randn(3,2)
a

tensor([[-0.4533,  0.2123],
        [-1.4178,  0.5631],
        [ 0.4261,  1.0870]])

In [26]:
numpy_a = a .numpy()
numpy_a

array([[-0.45329702,  0.21229936],
       [-1.417816  ,  0.56309295],
       [ 0.4261047 ,  1.08703   ]], dtype=float32)

In [27]:
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[-0.4533,  0.2123],
        [-1.4178,  0.5631],
        [ 0.4261,  1.0870]])

Tensor和numpy对象共享内存，所以他们之间的转换很快，而且几乎不会消耗什么资源。但这也意味着，如果其中一个变了，另外一个也会随之改变。

设备间转换
一般情况下可以使用.cuda方法将tensor移动到gpu，这步操作需要cuda设备支持

In [28]:
cpu_a = torch.rand(4,3)
cpu_a.type()

'torch.FloatTensor'

In [29]:
gpu_a = cpu_a.cuda()
gpu_a.type()

'torch.cuda.FloatTensor'

In [30]:
cpu_b = gpu_a.cpu()
cpu_b.type()

'torch.FloatTensor'

In [31]:
#使用torch.cuda.is_available()来确定是否有cuda设备
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
#将tensor传送到设备
gpu_b=cpu_b.to(device)
gpu_b.type()

cuda


'torch.cuda.FloatTensor'

初始化

In [32]:
rnd = torch.rand(5,3) #0-1的均匀分布
rnd

tensor([[0.0106, 0.4367, 0.5748],
        [0.0974, 0.5739, 0.3200],
        [0.1071, 0.0243, 0.8799],
        [0.6226, 0.2655, 0.0382],
        [0.5398, 0.0557, 0.7884]])

In [33]:
one = torch.ones(2,2)#使用1填充

In [34]:
one

tensor([[1., 1.],
        [1., 1.]])

In [35]:
zero = torch.zeros(2,2)#使用0填充

In [36]:
zero

tensor([[0., 0.],
        [0., 0.]])

In [37]:
eye = torch.eye(2,2)#初始化一个单位矩阵
eye

tensor([[1., 0.],
        [0., 1.]])

常用方法

In [38]:
x = torch.randn(3,3)
x

tensor([[-2.0338,  1.1807, -0.8962],
        [-0.2091,  0.1267, -1.8024],
        [ 0.4021, -0.0190, -0.5371]])

In [39]:
max_value,max_idx = torch.max(x,dim=1)#沿着行取最大值
print(max_value,max_idx)

tensor([1.1807, 0.1267, 0.4021]) tensor([1, 1, 0])


In [40]:
#每行X求和
sum_x = torch.sum(x,dim=1)
sum_x

tensor([-1.7493, -1.8848, -0.1541])

In [41]:
y = torch.randn(3,3)
z = x + y

In [42]:
z

tensor([[-2.5704,  2.0444, -0.9843],
        [ 0.6037, -0.3836, -3.5270],
        [ 0.6984, -1.2834, -2.5865]])

In [43]:
# add 完成后x的值改变了
x.add_(y)
print(x)

tensor([[-2.5704,  2.0444, -0.9843],
        [ 0.6037, -0.3836, -3.5270],
        [ 0.6984, -1.2834, -2.5865]])
