In [1]:
%matplotlib inline

Tensor和Numpy中的ndarrays类似，但是可以使用GPU加速运算

In [3]:
from __future__ import print_function
import torch

创建一个5*3的未初始化的矩阵

In [5]:
x = torch.empty(5,3)
x

tensor([[7.6225e-39, 1.0745e-38, 9.6429e-39],
        [9.6429e-39, 1.0745e-38, 1.0102e-38],
        [4.2246e-39, 1.0286e-38, 1.0653e-38],
        [1.0194e-38, 8.4490e-39, 1.0469e-38],
        [9.3674e-39, 9.9184e-39, 8.7245e-39]])

创建一个随机初始化的矩阵

In [6]:
x = torch.rand(5,3)
x

tensor([[0.3369, 0.4503, 0.9577],
        [0.8654, 0.4632, 0.1239],
        [0.6792, 0.9641, 0.2661],
        [0.7094, 0.8363, 0.6289],
        [0.6853, 0.5548, 0.8675]])

创建一个0填充的矩阵，数据类型为long

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

创建tensor并使用现有数据初始化

In [9]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

根据现有的张量创建张量，这些方法将重用输入张量的属性，例如dtype，除非设置新的值进行覆盖

In [10]:
x =x.new_ones(5,3,dtype=torch.double) #new_*方法创建新对象
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.randn_like(x,dtype=torch.float)
x               #覆盖类型，张量的size是相同的，只是值和类型发生了变化

tensor([[-0.6365, -1.1609,  0.3746],
        [-1.4800,  0.7312, -0.2178],
        [-1.5234, -0.2940,  0.3616],
        [ 0.4601, -0.0791, -0.8375],
        [-1.2666,  2.3300,  2.0058]])

In [12]:
x.size() #获取size

torch.Size([5, 3])

In [14]:
x.shape

torch.Size([5, 3])

加法运算

In [15]:
y = torch.rand(5,3)
y

tensor([[0.7175, 0.6109, 0.4798],
        [0.9644, 0.6812, 0.6044],
        [0.2620, 0.4331, 0.6304],
        [0.9137, 0.6521, 0.8277],
        [0.1760, 0.9905, 0.6634]])

In [16]:
x

tensor([[-0.6365, -1.1609,  0.3746],
        [-1.4800,  0.7312, -0.2178],
        [-1.5234, -0.2940,  0.3616],
        [ 0.4601, -0.0791, -0.8375],
        [-1.2666,  2.3300,  2.0058]])

In [17]:
x+y

tensor([[ 0.0810, -0.5500,  0.8545],
        [-0.5156,  1.4124,  0.3867],
        [-1.2614,  0.1390,  0.9920],
        [ 1.3738,  0.5730, -0.0098],
        [-1.0905,  3.3206,  2.6693]])

In [18]:
torch.add(x,y)

tensor([[ 0.0810, -0.5500,  0.8545],
        [-0.5156,  1.4124,  0.3867],
        [-1.2614,  0.1390,  0.9920],
        [ 1.3738,  0.5730, -0.0098],
        [-1.0905,  3.3206,  2.6693]])

提供输出的tensor作为参数


In [19]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[ 0.0810, -0.5500,  0.8545],
        [-0.5156,  1.4124,  0.3867],
        [-1.2614,  0.1390,  0.9920],
        [ 1.3738,  0.5730, -0.0098],
        [-1.0905,  3.3206,  2.6693]])

替换，任何以‘_’结尾的操作都会用结果替换原变量。


In [20]:
y.add_(x)
y

tensor([[ 0.0810, -0.5500,  0.8545],
        [-0.5156,  1.4124,  0.3867],
        [-1.2614,  0.1390,  0.9920],
        [ 1.3738,  0.5730, -0.0098],
        [-1.0905,  3.3206,  2.6693]])

In [21]:
x[:,1]

tensor([-1.1609,  0.7312, -0.2940, -0.0791,  2.3300])

torch.view和Numpy的reshape类似，可以改变张量的维度和大小


In [24]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) #size从-1 从其他维度推断 -1 类似变量 2*8=16
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果只有一个元素的张量，使用.item()得到python的数据类型

In [25]:
x = torch.randn(1)
x

tensor([-0.1512])

In [26]:
x.item()

-0.1511644572019577

Numpy转换
Tensor和Numpy数组共享底层内存地址，修改一个会导致另一个发生变化
将一个Tensor转换为Numpy数组

In [27]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [31]:
b = a.numpy()

In [32]:
a

tensor([2., 2., 2., 2., 2.])

In [33]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


numpy array 转换为tensor

In [34]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有的tensor类型默认都是基于CPU， charTensor类型不支持到Numpy的转换。CUDA张量使用.to方法可以将Tensor移动到任何设备中

In [35]:
if torch.cuda.is_available():
    device = torch.device('cuda') # 一个cuda设备对象
    y = torch.ones_like(x,device=device) #直接从GPU创建张量
    x = x.to(device)   #使用to方法将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to('cpu',torch.double)) # to也会对变量类型做修改

tensor([0.8488], device='cuda:0')
tensor([0.8488], dtype=torch.float64)
